# Generated by Django 6.0.6 on 2026-06-20 06:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0002_alter_user_options_user_username"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="book",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="book",
            name="genres",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="review_post",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="user",
        ),
        migrations.RemoveConstraint(
            model_name="reaction",
            name="unique_user_reaction",
        ),
        migrations.RemoveConstraint(
            model_name="reviewpost",
            name="unique_review_per_user_per_book",
        ),
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="trust_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_username",
                        message="Username can only contain letters, numbers, underscores, and hyphens.",
                        regex="^[a-zA-Z0-9_-]+$",
                    )
                ],
            ),
        ),
        migrations.DeleteModel(
            name="Genre",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.RemoveField(
            model_name="reviewpost",
            name="book",
        ),
        migrations.RemoveField(
            model_name="reviewpost",
            name="reviewer",
        ),
        migrations.DeleteModel(
            name="Reaction",
        ),
        migrations.DeleteModel(
            name="Book",
        ),
        migrations.DeleteModel(
            name="ReviewPost",
        ),
    ]
